[build]
  command = "gatsby build"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"